apiVersion: batch/v1
kind: Job
metadata:
  name: calqul-master-job-__NAMESPACE_ENV__
spec:
  # maximum duration the job can run => 40h 
  activeDeadlineSeconds: 144000 
  completions: 1
  backoffLimit: 2
  parallelism: 1
  template:         
    metadata:
      name: calqul-master-job-__NAMESPACE_ENV__
    spec:
      volumes:
      - name: arb-data
        persistentVolumeClaim: 
          claimName: pvc-01-__NAMESPACE__-claim
      containers:
      - name: calqul-python-__NAMESPACE_ENV__
        image: registry.forge.grandlyon.com/erasme/script-recalcul-calque/calqul-python-__NAMESPACE_ENV__
        env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secret-__NAMESPACE_ENV__
                key: password 
          - name: HTTP_PROXY
            value: "http://proxyhttppro.grandlyon.fr:8080"
          - name: HTTPS_PROXY
            value: "http://proxyhttppro.grandlyon.fr:8080"
        resources:
          requests:
            cpu: 1
            memory: 1000Mi
          limits:
            cpu: 1
            memory: 1000Mi
        volumeMounts:
        - name: arb-data
          mountPath: "/arb-data/source-files"
        - name: arb-data
          mountPath: "/arb-data/generated-files"
        - name: arb-data
          mountPath: "/arb-data/run" # storing a file telling export-job the state of python script
      restartPolicy: Never

      # Clone or update sources data before calculation
      initContainers:
      - name: init-data-repo
        image: registry.forge.grandlyon.com/erasme/script-recalcul-calque/calqul-git-lfs-__NAMESPACE_ENV__
        env:
          - name: GIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: arb-data-access-token
                key: username
          - name: GIT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: arb-data-access-token
                key: password
          - name: HTTP_PROXY
            value: "http://proxyhttppro.grandlyon.fr:8080"
          - name: HTTPS_PROXY
            value: "http://proxyhttppro.grandlyon.fr:8080"
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - if [ -d /arb-data/source-files/data-recalcul-calque/.git ]; then cd /arb-data/source-files/data-recalcul-calque; git pull origin main; else mkdir -p /arb-data/source-files/data-recalcul-calque; cd /arb-data/source-files; git lfs clone https://${GIT_USERNAME}:${GIT_PASSWORD}@forge.grandlyon.com/erasme/sources-recalcul-calque.git ./data-recalcul-calque/; fi; echo "Data ready !";
        # -  rm -rf /arb-data/source-files/data-recalcul-calque; mkdir -p /arb-data/source-files/data-recalcul-calque; cd /arb-data/source-files; git lfs clone https://arb-data-access-token:sj_-yDyc3nnvAmWmP76h@forge.grandlyon.com/erasme/sources-recalcul-calque.git ./data-recalcul-calque/;  echo "Data ready !"; 
        volumeMounts:
        - name: arb-data
          mountPath: "/arb-data/source-files"
        - name: arb-data
          mountPath: "/arb-data"
          subpath: "run"
