# 
# Job qui lance un pod de calcul des indices 
#
apiVersion: batch/v1
kind: Job
metadata:
  name: calqul-stage-__CALQUL_ACTION__-__NAMESPACE_ENV__
spec:
  # maximum duration the job can run => 160h 
  activeDeadlineSeconds: 576000
  completions: 1
  backoffLimit: 1
  parallelism: 1
  template:         
    metadata:
      name: calqul-stage-__CALQUL_ACTION__-__NAMESPACE_ENV__
    spec:
      volumes:
      - name: arb-data
        persistentVolumeClaim: 
          claimName: pvc-01-__NAMESPACE__-claim
      containers:
      - name: calqul-stage-__CALQUL_ACTION__-__NAMESPACE_ENV__
        # Image Python de calcul du calque
        image: registry.forge.grandlyon.com/erasme/script-recalcul-calque/calqul-python-__NAMESPACE_ENV__
        command: ["/bin/bash", "-c", "/app/launch.sh __CALQUL_ACTION__ __NAMESPACE_ENV__ __POSTGRES_SERVER__ __POSTGRES_PORT__ __POSTGRES_DB__ __POSTGRES_USER__" ]
        volumeMounts:
        - name: arb-data
          mountPath: "/arb-data/source-files"
        - name: arb-data
          mountPath: "/arb-data/generated-files"
        - name: arb-data
          mountPath: "/arb-data/run" # storing a file telling export-job the state of python script
        # Sondes
        env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secret-__NAMESPACE_ENV__
                key: password 
          - name: HTTP_PROXY
            value: "http://proxyhttppro.grandlyon.fr:8080"
          - name: HTTPS_PROXY
            value: "http://proxyhttppro.grandlyon.fr:8080"
        resources:
          requests:
            cpu: __CPU_REQUEST__  # 1
            memory: __MEM_REQUEST__ # 2000Mi
          limits:
            cpu: __CPU_LIMIT__ # 1
            memory: __MEM_LIMIT__ # 8000Mi
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - echo "OK"
            initialDelaySeconds: 240
            periodSeconds: 60
            failureThreshold: 3
            timeoutSeconds: 10
        livenessProbe: 
          exec:
            command:
            - /bin/bash
            - -c
            - echo "OK"
            initialDelaySeconds: 240
            periodSeconds: 60
            failureThreshold: 3
            timeoutSeconds: 10
      restartPolicy: Never