apiVersion: v1
kind: Service
metadata:
  name: calqul-db-service-__NAMESPACE_ENV__
  namespace: __NAMESPACE__
spec:
  type: NodePort
  selector:
    app: calqul-db-__NAMESPACE_ENV__
    tier: database
  ports:
    - name: http-5432
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30010 # Port d'exposition pour connexion d'un client vers le pod de base de données
