apiVersion: v1
kind: Service
metadata:
  name: calqul-db-service-${NAMESPACE_ENV}
  namespace: ${NAMESPACE}
spec:
  selector:
    app: calqul-db-${NAMESPACE_ENV}
    tier: database
  ports:
    - name: http-5432
      protocol: TCP
      port: 5432
      targetPort: 5432
