apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: arb-database-${NAMESPACE_ENV}-route
  namespace: ${NAMESPACE}
spec:
  host: arb-database-${NAMESPACE_ENV}-route-${NAMESPACE}.apps.air.grandlyon.fr
  to:
    kind: Service
    name: calqul-db-service-${NAMESPACE_ENV}
  port:
    targetPort: 5432
  tls:
    termination: edge
