apiVersion: batch/v1
kind: Job
metadata:
  name: calqul-job-__NAMESPACE_ENV__
spec:
  # maximum duration the job can run => 40h 
  activeDeadlineSeconds: 144000 
  template:         
    metadata:
      name: calqul-job-__NAMESPACE_ENV__
    spec:
      volumes:
      - name: arb-data
        persistentVolumeClaim: 
          claimName: pvc-01-__NAMESPACE__-claim
      containers:
      - name: calqul-python-__NAMESPACE_ENV__
        image: registry.forge.grandlyon.com/erasme/script-recalcul-calque/calqul-python-__NAMESPACE_ENV__
        volumeMounts:
        - name: arb-data
          mountPath: "/arb-data/source-files"
          # subpath: source-files
        - name: arb-data
          mountPath: "/arb-data/generated-files"
          # subpath: out
      restartPolicy: Never

      # Clone or update sources data before calculation
      initContainers:
      - name: update-data-source
        image: alpine/git:latest
        imagePullPolicy: IfNotPresent
        # command: ['/bin/sh', '-c', 'git clone https://forge.grandlyon.com/erasme/data-recalcul-calque.git /arb-data/source-files']
        command: ["sh", "-c", "until true; do echo 'Waiting until end of world...'; sleep 3; done;"]
        volumeMounts:
        - name: arb-data
          mountPath: "/arb-data/source-files"


  # Waiting for the Database POD to be ready. 
  # ~~ NOT SURE IT IS WORKING ??? ~~
  #
  # initContainers:
  # - name: wait-for-database
  #   image: busybox:latest
  #   imagePullPolicy: IfNotPresent
  #   command: ["sh", "-c", "until nc -vz ${POD_NAME}.${POD_NAMESPACE} __POSTGRES_PORT__; do echo "Waiting for ${POD_NAME} to get ready..."; sleep 3; done;"]
  #   env:
  #     - name: POD_NAME
  #       value: calqul-db-__NAMESPACE_ENV__
  #     - name: POD_NAMESPACE
  #       valueFrom:
  #         fieldRef:
  #           fieldPath: metadata.namespace