apiVersion: batch/v1
kind: Job
metadata:
  name: calqul-__NAMESPACE_ENV__
spec:
  activeDeadlineSeconds: 144000 # maximum duration the job can run => 40h 
  template:         
    metadata:
      name: calqul-__NAMESPACE_ENV__
    spec:
      containers:
      - name: calqul-__NAMESPACE_ENV__
        image: registry.forge.grandlyon.com/erasme/script-recalcul-calque/calqul-__NAMESPACE_ENV__
      restartPolicy: Never #OnFailure