apiVersion: batch/v1
kind: Job
metadata:
  name: calqul-__NAMESPACE_ENV__
spec:
  activeDeadlineSeconds: 144000 # maximum duration the job can run => 40h 
  template:         
    metadata:
      name: calqul-__NAMESPACE_ENV__
    spec:
      containers:
      - name: calqul-python-__NAMESPACE_ENV__
        image: registry.forge.grandlyon.com/erasme/script-recalcul-calque/calqul-python-__NAMESPACE_ENV__
        command:
          - cd /app; ./test-env.sh
          # - cd /app; python3 main.py 5 69266
      restartPolicy: Never