apiVersion: batch/v1
kind: Job
metadata:
  name: calqul-job-__NAMESPACE_ENV__
spec:
  # maximum duration the job can run => 40h 
  activeDeadlineSeconds: 144000 
  template:         
    metadata:
      name: calqul-job-__NAMESPACE_ENV__
    spec:
      volumes:
      - name: arb-data
        persistentVolumeClaim: 
          claimName: pvc-01-__NAMESPACE__-claim
      containers:
      - name: calqul-python-__NAMESPACE_ENV__
        image: registry.forge.grandlyon.com/erasme/script-recalcul-calque/calqul-python-__NAMESPACE_ENV__
        volumeMounts:
        - name: arb-data
          mountPath: "/arb-data/source-files"
          # subpath: source-files
        - name: arb-data
          mountPath: "/arb-data/generated-files"
          # subpath: out
      restartPolicy: Never

      # Clone or update sources data before calculation
      initContainers:
      - name: update-data-source
        image: registry.forge.grandlyon.com/erasme/script-recalcul-calque/calqul-git-lfs-__NAMESPACE_ENV__
        env:
          - name: GIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: arb-data-access-token
                key: username
          - name: GIT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: arb-data-access-token
                key: password
          - name: HTTP_PROXY
            value: "http://proxyhttppro.grandlyon.fr:8080"
          - name: HTTPS_PROXY
            value: "http://proxyhttppro.grandlyon.fr:8080"
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        # - ls -la /git; /git/update_data.sh
        # - mkdir -p /arb-data/source-files/data-recalcul-calque; cd /arb-data/source-files/data-recalcul-calque; [[ ! -d ".git" ]] && { echo "------ Pas de repo ------"; git init; git lfs install; git remote add origin https://${GIT_USERNAME}:${GIT_PASSWORD}@forge.grandlyon.com/erasme/sources-recalcul-calque.git; }; git checkout .; git pull origin main;
        - rm -rf /arb-data/source-files/data-recalcul-calque; mkdir -p /arb-data/source-files/data-recalcul-calque; cd /arb-data/source-files/; git lfs install --force; git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@forge.grandlyon.com/erasme/sources-recalcul-calque.git ./data-recalcul-calque/; cd data-recalcul-calque; git pull origin main;
        # git fetch origin; git checkout main
        volumeMounts:
        - name: arb-data
          mountPath: "/arb-data/source-files"