apiVersion: apps/v1
kind: Deployment
metadata:
  name: calqul-db-${NAMESPACE_ENV}
  namespace: ${NAMESPACE}
  labels:
    apps: calqul-db-${NAMESPACE_ENV}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calqul-db-${NAMESPACE_ENV}
      role: primary
      tier: database
  template:
    metadata:
      labels:
        app: calqul-db-${NAMESPACE_ENV}
        role: primary
        tier: database
    spec:
      imagePullSecrets:
        - name: forge-secret
      volumes:
        - name: arb-data
          persistentVolumeClaim: 
            claimName: ${POSTGRES_PVC_NAME}
      containers:
      - name: calqul-db-${NAMESPACE_ENV}
        image: registry.forge.grandlyon.com/erasme/script-recalcul-calque/calqul-db-${NAMESPACE_ENV}
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
          - name: POSTGRES_DB
            value: "${POSTGRES_DB}"
          - name: POSTGRES_PASSWORD
            value: "${POSTGRES_PASSWORD}"
          - name: POSTGRES_PORT
            value: "${POSTGRES_PORT}"
          - name: POSTGRES_SERVER
            value: "${POSTGRES_SERVER}"
          - name: POSTGRES_USER
            value: "${POSTGRES_USER}"
          - name: POSTGRES_SCHEMA
            value: "${POSTGRES_SCHEMA}"
            # need to define PGDATA env var because not using the default /var/lib/postgresql/data, but a subpath under it.
          - name: PGDATA
            value: /arb-data/pgdata
        resources:
          limits:
            cpu: 400m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
          # need a subpath as postgres wants an empty folder (the mounted folder `$PGDATA` has a `lost+found` directory)
          # see https://stackoverflow.com/questions/51168558/how-to-mount-a-postgresql-volume-using-aws-ebs-in-kubernete
          - name: arb-data
            mountPath: "/arb-data"
            subpath: pgdata
