#
# Pod d'accès au PVC. Utile pour remettre l'environnement de travail à blanc, y compris les fichiers Postgres.
# 
kind: Deployment
apiVersion: apps/v1
metadata:
  name: calqul-pvc-${NAMESPACE_ENV}
  namespace: ${NAMESPACE}
  labels:
    app: calqul-pvc-${NAMESPACE_ENV}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calqul-pvc-${NAMESPACE_ENV}
      role: secondary
      tier: exploitation  
  template:
    metadata:
      labels:
        app: calqul-pvc-${NAMESPACE_ENV}
        role: secondary
        tier: exploitation
    spec:
      containers:
        - name: calqul-pvc-${NAMESPACE_ENV}
          image: registry.gitlab.grandlyon.fr/openshift-as-code/reposit-gl/busybox:1.0
          command: ["sh", "-c", "watch -n 30 df -h | grep /mnt/data"]
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /mnt/data
              name: data
            - mountPath: /mnt/data2
              name: data2
      resources:
        requests:
          memory: "32M"
          cpu: "100mi"
        limits:
          memory: "64M"
          cpu: "100mi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-02-${NAMESPACE}-claim
        - name: data2
          persistentVolumeClaim:
            claimName: pvc-03-${NAMESPACE}-claim
            