apiVersion: apps/v1
kind: Deployment
metadata:
  name: calqul-qgis-server-__NAMESPACE_ENV__
  namespace: __NAMESPACE__
  labels:
    apps: calqul-qgis-server-__NAMESPACE_ENV__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calqul-qgis-server-__NAMESPACE_ENV__
      role: primary
      tier: database
  template:
    metadata:
      labels:
        app: calqul-qgis-server-__NAMESPACE_ENV__
        role: primary
        tier: database
    spec:
      imagePullSecrets:
        - name: forge-secret
      volumes:
        - name: arb-data
          persistentVolumeClaim: 
            claimName: pvc-01-__NAMESPACE__-claim
      containers:
      - name: calqul-qgis-server-__NAMESPACE_ENV__
        image: camptocamp/qgis-server:3.30
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        # readinessProbe:
        #   tcpSocket:
        #     port: 5432
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        # livenessProbe:
        #   tcpSocket:
        #     port: 5432
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        resources:
          limits:
            cpu: 400m
            memory: 600Mi
          requests:
            cpu: 200m
            memory: 256Mi
        env:
        - name: POSTGRES_DB
          value: "__POSTGRES_DB__"
        - name: POSTGRES_PASSWORD
          value: "__POSTGRES_PASSWORD__"
        - name: POSTGRES_PORT
          value: "__POSTGRES_PORT__"
        - name: POSTGRES_SERVER
          value: "__POSTGRES_SERVER__"
        - name: POSTGRES_USER
          value: "__POSTGRES_USER__"
        - name: POSTGRES_SCHEMA
          value: "__POSTGRES_SCHEMA__"
        volumeMounts:
          - name: arb-data
            mountPath: "/arb-data"
            subpath: qgis_conf
